# This schema file is automatically generated by `rake db:schema`.
# It will be overwritten periodically so do not make changes.
Sequel.migration do
  change do
    create_table(:applications) do
      primary_key :id
      String :username, :size=>255, :null=>false
      String :app_name, :size=>255, :null=>false
      String :app_description, :size=>255
    end
    
    create_table(:gateways) do
      primary_key :id
      String :gateway_name, :size=>255, :null=>false
      String :gateway_mac, :size=>255, :null=>false
      String :gateway_ip, :size=>255, :null=>false
      String :gateway_loc, :size=>255, :null=>false
      String :username, :size=>255, :null=>false
    end
    
    create_table(:nodes) do
      primary_key :id
      String :username, :size=>255, :null=>false
      String :app_name, :size=>255, :null=>false
      String :node_addr, :size=>255, :null=>false
      String :node_nwkskey, :size=>255, :null=>false
      String :node_appskey, :size=>255, :null=>false
    end
    
    create_table(:nodes_data) do
      primary_key :id
      Integer :channel
      Integer :sf
      String :time, :size=>255
      String :gwip, :size=>255
      String :gwid, :size=>255
      String :repeater, :size=>255
      Integer :systype
      Float :rssi
      Float :snr
      Float :snr_max
      Float :snr_min
      String :macAddr, :size=>255
      String :data, :size=>255
      Integer :frameCnt
      Integer :fport
    end
    
    create_table(:schema_info) do
      Integer :version, :default=>0, :null=>false
    end
    
    create_table(:users) do
      primary_key :id
      String :username, :size=>255, :null=>false
      String :user_email, :size=>255, :null=>false
      String :password, :size=>255, :null=>false
    end
  end
end
